version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

      - store_artifacts:
          name: Uploading rendering artifacts
          path: rendering/cases/
          destination: rendering

      - run:
          name: Build Examples
          command: npm run build-examples

      - store_artifacts:
          name: Uploading examples artifacts
          path: build/examples
          destination: examples

      - run:
          name: Run benchmarks
          command: npm run benchmarks

      - store_artifacts:
          name: Uploading benchmarks artifacts
          path: rendering/benchmarks/
          destination: benchmarks
